### ISSUE TITLE
Not able to compile ZeroMQ. Calls from Red(not System): handle! != byte-ptr!

### ISSUE THREAD

**Issue by Intey** [red/code#82]
Hello.
OS: Windows 10
Red version:  0.6.4
ZeroMQ version: 4.3.2
I'm try to start ZeroMQ socket(server?) from red(not Red/System), but can't compile this [gist](https://gist.github.com/Intey/1a851ba6e710e911881dcd77b5c46ed7):
> Compiling to native code...
*** Warning: handle! macro in R/S is redefined
*** Compilation Error: argument type mismatch on calling: exec/zmq/socket
*** expected: [pointer! [byte!]], found: [pointer! [integer!]]
*** in file: %/D/Dima/projects/red-ipython/red/src/kernel.red
*** in function: exec/start-server
*** at line: 381
*** near: [ctx 4
    print-line ["ZMQ Context:   " ctx]
    print-line ["ZMQ Responder: " responder]
    r: zmq/bind
]

It's can be fixed, with changes on [this line](https://github.com/red/code/blob/master/Library/ZeroMQ/ZeroMQ.reds#L212) from
```red
ctx_new: "zmq_ctx_new" [ return: [handle!]]
```
to 
```red
ctx_new: "zmq_ctx_new" [ return: [byte-ptr!]]
```
and after this change, it's compile and server starts. I'm not tested yet this with client requests.
I can prepare PR with this fix, if it's ok.

**Comment by 9214** [comment]
Change of a single line is not enough, as there are other usages of `handle!` in the source code, nor does it solve the actual problem.

Red/System rightfully warns you and rejects such macro redefinition (that's the reason of compilation error - there's a type mismatch in library call, because old definition is still being used), as it's a ticking bomb that may cause serious trouble, e.g. Red runtime relies on `handle!` pretty heavily, esp. in OS APIs.

Anyway, this code is not maintained for a long time and serves only as a PoC, you shouldn't use it as-is for your project. Red itself will likely have ZeroMQ port in the future.

**Comment by Intey** [comment]
Yes, i understood that it's not nice fix. 
And i'm ok with that not maintained - i too just playing with red (try to implement IPython kernel with red). 
It's ok, to change `handle!` definition to something another name or remove it?

**Comment by 9214** [comment]
@Oldes ☝️

**Comment by Oldes** [comment]
@Intey what if you just remove this line?

https://github.com/red/code/blob/95a4b1632d321f4afcf354dce3668ae0e20c1bf0/Library/ZeroMQ/ZeroMQ.reds#L18

Apparently there was no `handle!` used in Red's runtime when I was working with it.

**Comment by Oldes** [comment]
As in the source is `handle!` used mostly instead of `void *`, it should be ok.

**Comment by Intey** [comment]
@Oldes I think about this. But I meet nice idea of name types explicit. Something like `context-ptr!` like with `socket-ptr!`. I prepare PR to show this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
